sudo: required
services:
  - docker

before_install:
  - docker build -t qh4r/travis-tests -f Dockerfile.dev .

script:
  - docker run -e CI=true qh4r/travis-tests npm run test
# CI zeby wyszedl po dopaleniu testow

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "travis-app"
  env: "TravisApp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-644539583708"
  bucket_path: "travis-app" #default equal to app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
