sudo: required
services:
  - docker

before_install:
  - docker build -t qh4r/travis-tests -f Dockerfile.dev .

script:
  - docker run -e CI=true qh4r/travis-tests npm run test
# CI zeby wyszedl po dopaleniu testow
