sudo: required
services:
  - docker

before_install:
  - docker build -t qh4r/travis-tests -f Dockerfile.dev .

script:
  - docker run qh4r/travis-tests CI=true npm run test
# CI zeby wyszedl po dopaleniu testow
